# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

max_error <- function(a, b, n = 0L) {
    .Call(`_fddm_max_error`, a, b, n)
}

almost_equal <- function(a, b, thresh = 0.0) {
    .Call(`_fddm_almost_equal`, a, b, thresh)
}

nearly_equal <- function(a, thresh = 0.0) {
    .Call(`_fddm_nearly_equal`, a, thresh)
}

ks_BGK <- function(t, a, w, eps) {
    .Call(`_fddm_ks_BGK`, t, a, w, eps)
}

ks_Nav <- function(t, a, eps) {
    .Call(`_fddm_ks_Nav`, t, a, eps)
}

kl_Nav <- function(t, a, eps) {
    .Call(`_fddm_kl_Nav`, t, a, eps)
}

small_sum_2014 <- function(t, a, w, ks) {
    .Call(`_fddm_small_sum_2014`, t, a, w, ks)
}

small_sum_2017 <- function(t, a, w, ks) {
    .Call(`_fddm_small_sum_2017`, t, a, w, ks)
}

small_sum_eps_14 <- function(t, a, w, mult, eps) {
    .Call(`_fddm_small_sum_eps_14`, t, a, w, mult, eps)
}

small_sum_eps_17 <- function(t, a, w, mult, eps) {
    .Call(`_fddm_small_sum_eps_17`, t, a, w, mult, eps)
}

large_sum_Nav <- function(t, a, w, kl) {
    .Call(`_fddm_large_sum_Nav`, t, a, w, kl)
}

fs_eps_2014 <- function(rt, resp, v, a, w, t0 = 0.0, eps = 0.0) {
    .Call(`_fddm_fs_eps_2014`, rt, resp, v, a, w, t0, eps)
}

fs_eps_2017 <- function(rt, resp, v, a, w, t0 = 0.0, eps = 0.0) {
    .Call(`_fddm_fs_eps_2017`, rt, resp, v, a, w, t0, eps)
}

fs_Nav_2014 <- function(rt, resp, v, a, w, t0 = 0.0, eps = 0.0) {
    .Call(`_fddm_fs_Nav_2014`, rt, resp, v, a, w, t0, eps)
}

fs_Nav_2017 <- function(rt, resp, v, a, w, t0 = 0.0, eps = 0.0) {
    .Call(`_fddm_fs_Nav_2017`, rt, resp, v, a, w, t0, eps)
}

fs_BGK_2014 <- function(rt, resp, v, a, w, t0 = 0.0, eps = 0.0) {
    .Call(`_fddm_fs_BGK_2014`, rt, resp, v, a, w, t0, eps)
}

fs_BGK_2017 <- function(rt, resp, v, a, w, t0 = 0.0, eps = 0.0) {
    .Call(`_fddm_fs_BGK_2017`, rt, resp, v, a, w, t0, eps)
}

fl_Nav <- function(rt, resp, v, a, w, t0 = 0.0, eps = 0.0) {
    .Call(`_fddm_fl_Nav`, rt, resp, v, a, w, t0, eps)
}

fb_Nav_Nav_14 <- function(rt, resp, v, a, w, t0 = 0.0, eps = 0.0) {
    .Call(`_fddm_fb_Nav_Nav_14`, rt, resp, v, a, w, t0, eps)
}

fb_Nav_Nav_17 <- function(rt, resp, v, a, w, t0 = 0.0, eps = 0.0) {
    .Call(`_fddm_fb_Nav_Nav_17`, rt, resp, v, a, w, t0, eps)
}

fb_BGK_Nav_14 <- function(rt, resp, v, a, w, t0 = 0.0, eps = 0.0) {
    .Call(`_fddm_fb_BGK_Nav_14`, rt, resp, v, a, w, t0, eps)
}

fb_BGK_Nav_17 <- function(rt, resp, v, a, w, t0 = 0.0, eps = 0.0) {
    .Call(`_fddm_fb_BGK_Nav_17`, rt, resp, v, a, w, t0, eps)
}

fs_vary <- function(rt, resp, v, a, w, sv = 0.0, t0 = 0.0, eps = 0.0) {
    .Call(`_fddm_fs_vary`, rt, resp, v, a, w, sv, t0, eps)
}

rcpp_hello_world <- function() {
    .Call(`_fddm_rcpp_hello_world`)
}

