# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dfddm <- function(rt, response, a, v, t0, w, sv, sigma, log_prob, n_terms_small, summation_small, scale, max_terms_large, eps) {
    .Call(`_fddm_cpp_dfddm`, rt, response, a, v, t0, w, sv, sigma, log_prob, n_terms_small, summation_small, scale, max_terms_large, eps)
}

