# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dfddm_fast <- function(rt, a, v, t0, w, eps) {
    .Call(`_fddm_cpp_dfddm_fast`, rt, a, v, t0, w, eps)
}

cpp_dfddm <- function(rt, response, a, v, t0, w, sv, log_prob, n_terms_small, summation_small, scale, eps) {
    .Call(`_fddm_cpp_dfddm`, rt, response, a, v, t0, w, sv, log_prob, n_terms_small, summation_small, scale, eps)
}

